version: 2

models:
  - name: dim_police_areas
    description: "Lookup of police areas"
    columns:
      - name: police_area_id
        description: "Surrogate key for police area"
        tests: [not_null, unique]
      - name: police_area_name
        description: "Name of the police area"
      - name: main_police_areas_code
        description: "Truncated code (first 2 chars) of the police area UID"

  - name: dim_crime_types
    description: "Lookup of crime types"
    columns:
      - name: crime_type_id
        description: "Surrogate key for crime type"
        tests: [not_null, unique]
      - name: crime_code
        description: "Original crime code"
        tests: [not_null]
      - name: crime_description
        description: "Description of the crime"
        tests: [not_null]
      - name: part_1_2
        description: "None"

  - name: dim_mo_codes
    description: "Lookup of modus operandi codes"
    columns:
      - name: mo_code_id
        description: "Surrogate key for MO code"
        tests: [not_null, unique]
      - name: mo_description
        description: "Description of the modus operandi"

  - name: dim_location_types
    description: "Lookup of location types"
    columns:
      - name: location_type_id
        description: "Surrogate key for location type"
        tests: [not_null, unique]
      - name: original_premis_code
        description: "Original premis_cd from source"
        tests: [not_null]
      - name: location_type_description
        description: "Textual description of the location type"

  - name: dim_case_status
    description: "Lookup of case statuses"
    columns:
      - name: case_status_id
        description: "Surrogate key for case status"
        tests: [not_null, unique]
      - name: case_status_description
        description: "Description of the case status"

  - name: dim_weapons
    description: "Lookup of weapon types"
    columns:
      - name: weapon_id
        description: "Surrogate key for weapon"
        tests: [not_null, unique]
      - name: weapon_desc
        description: "Original weapon description from source"

  - name: dim_locations
    description: "Lookup of location details"
    columns:
      - name: location_id
        description: "Surrogate key for location"
        # tests: [not_null, unique]
      - name: location_cross_street
        description: "Cross-street information"
      - name: locations_latitude
        description: "Latitude coordinate"
      - name: locations_longitude
        description: "Longitude coordinate"
